'use client'

import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import "../../public/fonts/pretendard.css";
import {ThemeProvider} from '@mui/material'
import {theme} from '../libs/theme'

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <ThemeProvider theme={theme}>
      <body>{children}</body>
    </ThemeProvider>
    </html>
  );
}
